/** All interface copy (English only). Event texts live in @orbit/core/events. */
import type { PlanetClass } from "@orbit/core";

export const copy = {
  agency: "Deep Space Network",
  /** Credit for the AI that writes the stories (text only: no Anthropic logos). */
  claude: {
    badge: "Powered by Claude",
    note: "Every news story, chronicle and culture is written by Claude, an AI by Anthropic.",
    url: "https://www.anthropic.com/claude",
  },
  program: "Holder Exploration Program",
  h1: ["Every holder", "is a world."],
  heroP:
    "Your rank sets the size of your planet. Time held makes it calmer and luckier, but every world lives its own unpredictable story.",
  searchPh: "Paste a wallet address or planet name",
  searchLabel: "Wallet address or planet name",
  find: "Find",
  random: "Fly to a random world",
  top1: "Visit #1",
  notFound: "No planet for that address yet. A planet forms after the first buy.",
  gfeedH: "Mission news",
  legendH: "How the system works",
  legendRule: {
    size: "Size",
    sizeText: " = your rank among holders. ",
    distance: "Distance",
    distanceText: " = time held, oldest closest to the star.",
  },
  legend: [
    ["Supergiant", "#1"],
    ["Gas giants", "#2–10"],
    ["Ice giants", "#11–50"],
    ["Rocky worlds", "#51–200"],
    ["Asteroids", "#201+"],
  ],
  tele: {
    utc: "UTC",
    met: "Mission time",
    objects: "Objects",
    star: "Star",
    mcap: "Market cap",
  },
  demo: "Demo data",
  rules: "Rules",
  faq: "FAQ",
  menu: "Menu",
  rulesLink: "Read the mission rules",
  buy: (ticker: string) => `Buy $${ticker}`,
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  zoomFit: "Show whole system",
  quality: "Graphics quality",
  qualityNames: { auto: "Auto", high: "High", medium: "Medium", low: "Low" },
  canvasLabel: "3D star system where each planet is a token holder",
  loading: "Establishing link…",
  slowLoad: "Still loading the 3D engine. Check your connection or try reloading.",
  noWebgl: "WebGL is not available on this device, so the 3D system can't be shown.",
  textView: {
    eyebrow: "Text view",
    title: "The system as a list",
    note: "3D graphics are not available on this device, so every world is listed here. Open one to see its full mission page.",
    worlds: "Worlds",
    none: "No world matches.",
    more: (n: number) => `Show more (${n.toLocaleString("en-US")} left)`,
  },
  sceneError: (msg: string) =>
    `The 3D scene could not start: ${msg}. Try a desktop browser with WebGL enabled.`,
  missionPage: "Mission page",

  cls: {
    super: "Supergiant",
    gas: "Gas giant",
    ice: "Ice giant",
    rocky: "Rocky world",
    asteroid: "Asteroid",
  } satisfies Record<PlanetClass, string>,
  clsPl: {
    super: "Supergiant",
    gas: "Gas giants",
    ice: "Ice giants",
    rocky: "Rocky worlds",
    asteroid: "Asteroids",
  } satisfies Record<PlanetClass, string>,

  theCoin: "The coin",
  classX: "Class",
  copyCA: "Copy CA",
  copyBtn: "Copy",
  copied: "Copied",
  selectedT: "Selected",
  starLore:
    "The star is the coin itself. It grows and changes colour as market cap crosses each threshold. Every world in the system orbits it.",
  mcap: "Market cap",
  worldsOrbit: "Worlds in orbit",
  spectral: "Spectral class",
  nextEvo: "Next evolution",
  max: "Max",
  fully: "Fully evolved",
  supply: "Total supply",
  ignition: "Ignition",
  evo: "Stellar evolution",
  evoNow: "Now",
  starRules: "How the star grows",
  under: "under ",
  flyCloser: "Fly closer",

  kardashev: "Kardashev",
  temp: "Temperature",
  water: "Water",
  atm: "Atmosphere",
  atmU: "atm",
  life: "Life",
  bio: "Biosphere",
  speciesU: "species",
  pop: "Population",
  noCiv: "No civilization",
  tech: "Technology",
  stab: "Stability",
  stabHint: "Grows with time held. Lowers the odds of disasters.",
  newsMore: "Show older news",
  newsNone: "No news yet.",
  civH: "Civilization",
  civNone:
    "No civilization yet. If one appears, its species, capital and beliefs will be described here.",
  speciesL: "Species",
  typeL: "Type",
  lookL: "Appearance",
  capitalL: "Capital",
  ideologyL: "Beliefs",
  mottoL: "Motto",
  aiH: "Mission report · AI chronicler",
  aiCredit: (when: string) => `Written by Claude from this planet's facts and news · ${when}`,
  aiPending:
    "The chronicler is reading this planet's facts and news. Its story will appear here shortly.",
  aiDemo: "Chronicles are written for live planets once the coin launches.",
  /* wallet and customisation */
  connect: "Connect wallet",
  myPlanet: "My planet",
  logout: "Log out",
  moderation: "Moderation",
  walletH: "Connect a wallet",
  walletNote:
    "A wallet is only needed to customize your own planet. You sign a short text message: we will never ask you to sign a transaction.",
  noWallets: "No Solana wallet was found in this browser.",
  installPhantom: "Get Phantom",
  installSolflare: "Get Solflare",
  openPhantom: "Open in Phantom",
  openSolflare: "Open in Solflare",
  signing: "Check your wallet and sign the message…",
  signedIn: (addr: string) => `Signed in as ${addr}`,
  close: "Close",
  noPlanetYet: (ticker: string, min: string) =>
    `This wallet has no planet yet. Hold at least ${min} $${ticker} to get one.`,
  customize: "Customize planet",
  editH: "Customize planet",
  fName: "Planet name",
  fSpecies: "Species name",
  fCapital: "Capital",
  fMotto: "Motto",
  fCivLater: "Species, capital and motto take effect once a civilization appears on the planet.",
  fNote:
    "Only you can change your planet. Names are checked and can be changed once a day. Empty fields use the stock names.",
  save: "Save",
  cancel: "Cancel",
  reset: "Restore defaults",
  saved: "Saved. Your names now appear everywhere on the site.",
  restored: "Stock names restored.",
  reportName: "Report name",
  reportQ: "Report this planet's names as offensive? A moderator will review them.",
  reportReason: "Reason (optional)",
  reportSend: "Send report",
  reported: "Thanks. A moderator will take a look.",
  findsH: "Rare finds",
  findsNone: "Nothing yet. Rare finds turn up about once a year of planet time.",
  tokens: "Tokens",
  share: "Share of supply",
  since: "Holder since",
  buysSells: "Buys / sells",
  distance: "Distance",
  au: "AU",
  year: "Year length",
  daysU: "days",
  days: (n: number) => `${n} days`,
  hours: (n: number) => `${n} h`,
  achievements: "Achievements",
  badges: [
    ["OG Settler", "Among the first 50 holders"],
    ["Diamond Core", "30+ days, never sold"],
    ["Top 10", "Ranked in the top 10"],
    ["Cradle of life", "Life appeared within 3 days"],
    ["Ring-world", "Reached the Megastructure era"],
    ["Survivor", "Lived through a catastrophe"],
    ["Collector", "Owns a rare find"],
  ],
  ago: {
    now: "just now",
    h: (n: number) => `${n} h ago`,
    d: (n: number) => `${n} d ago`,
  },
  dayN: (n: number) => `Day ${n}`,
  back: "Back to system",
  system: "System",
  active: "Active",
  fastFacts: "Fast facts",
  newsH: "Mission news",
  timelineH: "Mission timeline",
  holderH: "Holder data",
  rankL: "Rank",
  orbitNo: "Orbit",
  ofN: (n: string) => `of ${n}`,
  perDay: "% / day",
  present: "Present",
  sinceDay: (d: number) => `since day ${d}`,
  noLifeYet: "none yet",
  lifeImpossible: "conditions unsuitable",
  starH: "The star",
  lostH: "Lost worlds",
  destroyed: "Destroyed",
  destroyedLede:
    "The holder sold everything. The planet broke apart; its debris will drift in this orbit for a day. A new world forms if they buy back in.",
  lastRecord: "Last record",
  lastEra: "Last era",
  lived: "Lived",
  debris: "Debris",
} as const;

export const LOCALE = "en-GB";

/** Mission rules page (/rules). Numbers are passed in from the game config. */
/** Moderation page (admins only). */
export const adminCopy = {
  title: "Name reports",
  lede: "Planets whose custom names were reported. Hiding them shows the stock names everywhere; the owner can choose new names after a day.",
  loading: "Loading…",
  signIn: "Connect an admin wallet to see the reports.",
  notAdmin: "This wallet is not a moderator.",
  empty: "No open reports. All quiet in orbit.",
  loadError: "Reports could not be loaded.",
  actionError: "That did not work. Reload the page and try again.",
  reports: (n: number) => (n === 1 ? "1 report" : `${n} reports`),
  stock: "Stock name",
  wallet: "Wallet",
  fields: { name: "Name", species: "Species", capital: "Capital", motto: "Motto" },
  hide: "Hide names",
  dismiss: "Keep names",
};

export const rulesCopy = {
  title: "Mission rules",
  metaDescription:
    "How ORBIT works: who becomes a planet, what sets its size and orbit, how the simulation runs and what selling does.",
  eyebrow: "Flight rules · Holder Exploration Program",
  h1: ["How a world is born,", "grows and falls."],
  lede: "Every holder of the coin is a planet orbiting the coin-star. The chain decides who you are in the system. The simulation decides what happens to your world. Here is the whole rulebook.",
  back: "Back to system",
  toc: "Contents",
  rules: {
    entry: {
      tag: "Rule 01",
      title: "Entry: hold the minimum",
      lead: (min: string, ticker: string) =>
        `Hold at least ${min} $${ticker} in one wallet and a planet forms for you.`,
      points: (min: string) => [
        `Below ${min} tokens there is no planet: small balances stay as dust in the belt.`,
        "Your wallet is what counts. Tokens spread across several token accounts of the same wallet are added together.",
        `If your balance drops below ${min}, your planet is destroyed, exactly as after a full sell.`,
      ],
      gaugeLabel: "Wallet balance",
      dust: "Dust",
      world: "World forms",
    },
    size: {
      tag: "Rule 02",
      title: "Size = your rank",
      lead: "Your place by balance among all holders sets the class and size of your planet.",
      points: [
        "Ranks are recalculated with every chain snapshot, about once a minute.",
        "When your rank changes, your planet grows or shrinks smoothly.",
      ],
    },
    orbit: {
      tag: "Rule 03",
      title: "Orbit = time held",
      lead: "The longer you hold, the closer you orbit the star. The oldest holder flies nearest.",
      points: [
        "Your hold starts the moment your balance first reaches the minimum.",
        "Buying more never resets your hold start.",
        "Orbits move on a shared clock, so every visitor sees every planet in the same place.",
      ],
      legendOld: "Oldest holders",
      legendNew: "Newest holders",
    },
    sim: {
      tag: "Rule 04",
      title: "The simulation never sleeps",
      lead: (hours: number) =>
        `Every ${hours} hours your planet takes one step of its own history, counted from the start of your hold.`,
      points: (chance: number, astChance: number) => [
        `Each step has a ${chance}% chance of an event: volcanoes, comets, ice ages, wars, golden ages, elections and more (asteroids: about ${astChance}%).`,
        "Time held raises stability. Stable worlds suffer fewer disasters and grow faster.",
        "Bigger planets get a bonus to stability and technology; #1 gets the most.",
        "Life, cities and spaceflight are never guaranteed. Some worlds stay barren forever.",
        "Very rarely a world makes a discovery that stays in its collection for good.",
      ],
      clock: "One step",
      erasTitle: "Eras of a world",
      erasNote: "Eras can also go backwards after wars, pandemics and catastrophes.",
    },
    sell: {
      tag: "Rule 05",
      title: "Selling hits your world",
      lead: "Every sell is measured against your balance just before it. The bigger the share, the harder the strike.",
      ignore: (pct: string) => `under ${pct}: nothing happens`,
      tierRange: (from: string, to: string) => `${from} to under ${to}`,
      tierFull: "100%: everything sold",
      points: (pct: string) => [
        `Sells under ${pct} of your balance go unnoticed.`,
        "A strike lands on your planet's next step: population, biosphere, technology and stability roll back.",
        "Sending tokens to another wallet counts as a sell for you and a buy for the receiver.",
        "Buying never hurts: top-ups only add to your balance.",
      ],
    },
    death: {
      tag: "Rule 06",
      title: "Death and rebirth",
      lead: "Sell everything, or fall below the minimum, and your planet is destroyed.",
      points: [
        "A cloud of debris stays in its orbit for 24 hours.",
        "Its history goes to the archive and is never lost.",
        "Buy back in and a new world forms: the same look (it comes from your address), but progress and hold time start from zero.",
      ],
    },
    rings: {
      tag: "Rule 07",
      title: "Rings and honours",
      lead: (days: number) =>
        `Hold for ${days} days without a single sell and your world earns rings.`,
      points: [
        "Achievements mark the first settlers, diamond hands, the top 10, early life, ring-worlds, survivors and collectors.",
      ],
    },
    star: {
      tag: "Rule 08",
      title: "The star is the coin",
      lead: "The star at the centre is the coin itself. It changes class as the market cap crosses each threshold.",
      under: "under",
      over: "and above",
    },
    news: {
      tag: "Rule 09",
      title: "News from the facts",
      lead: "Mission news reports what the simulation decided. Every number in a story comes from the simulation itself.",
      points: [
        "News appears live, without reloading the page.",
        "Stories never mention prices or give buying or selling advice.",
      ],
    },
    owner: {
      tag: "Rule 10",
      title: "Your planet, your names",
      lead: "Connect your wallet and sign a message to name your planet, species, capital and motto.",
      points: [
        "Only the owner of a planet can change it, once a day. Empty fields keep the stock names.",
        "We will never ask you to sign a transaction. Signing in only proves you own the wallet.",
        "Names are checked for abuse and can be reported; a moderator can hide them.",
        "Your names appear everywhere: on the map, in search, in every news story and in the chronicle.",
      ],
    },
    excluded: {
      tag: "Rule 11",
      title: "Who is not a planet",
      lead: "Some accounts hold tokens but are not people. They never appear in the system:",
      points: ["the bonding curve and liquidity pools (program accounts),", "the burn address."],
    },
  },
  disclaimer:
    "ORBIT is an entertainment visualisation. Planets, civilizations and events have no monetary value and are not financial advice.",
  cta: "Find your planet",
} as const;

/** FAQ and disclaimer page. Numbers come from the balance config and the token. */
export const faqCopy = {
  title: "FAQ",
  metaDescription:
    "Questions about ORBIT: how to get a planet, what selling does, wallet safety, AI news and the disclaimer.",
  eyebrow: "Mission briefing",
  h1: "Questions & answers",
  lede: "Everything a new crew member asks first. The full rules of the game are on the rules page.",
  rulesLink: "Read the mission rules",
  tag: "Question",
  items: (p: { ticker: string; min: string; ignore: string; rings: number }) => [
    {
      q: "What is ORBIT?",
      a: [
        `A live star system built from the $${p.ticker} token. The star is the coin itself and grows with its market cap. Every holder is a planet that lives its own simulated history: oceans, life, cities, wars, discoveries.`,
      ],
    },
    {
      q: "How do I get a planet?",
      a: [
        `Hold at least ${p.min} $${p.ticker} in one wallet. A planet forms a few seconds after the purchase reaches the blockchain, at the outer edge of the system.`,
        "The longer you hold, the closer your orbit, the further your world develops and the more stable it becomes.",
      ],
    },
    {
      q: "What happens if I sell?",
      a: [
        `Sells strike your planet: the bigger the share sold, the harder the catastrophe, from a meteor strike to an extinction event. Sells under ${p.ignore} of your balance go unnoticed.`,
        "Selling everything destroys the planet. A cloud of debris stays on its orbit for 24 hours, and its story goes to the archive. Buying again starts a brand new planet from scratch.",
      ],
    },
    {
      q: "Is a transfer to another wallet a sell?",
      a: [
        "Yes. A transfer counts as a sell for the sender and a buy for the receiver, exactly as the blockchain records it. Moving tokens between your own wallets therefore hits the planet of the wallet you move them from.",
      ],
    },
    {
      q: "Why does my planet change size?",
      a: [
        "Size follows your current rank among holders: the biggest holders are giants, the smallest are asteroids. The nature of a planet (rocky, gas, ice or asteroid world) is fixed at birth and never changes.",
      ],
    },
    {
      q: "Is connecting my wallet safe?",
      a: [
        "We will never ask you to sign a transaction. Connecting is only needed to customize your own planet: you sign a short text message that proves you own the wallet. It costs nothing, moves no tokens and gives the site no permissions.",
        "Watching the system needs no wallet at all.",
      ],
    },
    {
      q: "Can I rename my planet?",
      a: [
        "Yes: connect the wallet that holds the planet, open it and press Customize planet. You can set the planet name, species, capital and motto once a day. Names are checked for abuse and can be reported.",
      ],
    },
    {
      q: "What does Claude do in ORBIT?",
      a: [
        "ORBIT is powered by Claude, an AI by Anthropic. Claude turns what happens on every planet into press releases, writes the culture of each new civilization and the chronicle of every world, so each holder's planet has its own story.",
      ],
    },
    {
      q: "Who writes the news?",
      a: [
        "The simulation decides everything that happens. Claude, an AI by Anthropic, then writes the press releases and chronicles from those facts, keeping every number exactly as the simulation produced it. If the AI is unavailable, short template texts are shown instead.",
      ],
    },
    {
      q: "Why don't I see my wallet?",
      a: [
        `Check that it holds at least ${p.min} $${p.ticker}; smaller balances do not form a planet. New planets appear within seconds, in rare cases within a minute. Program accounts such as liquidity pools and the burn address never appear.`,
      ],
    },
    {
      q: "What do rings and achievements mean?",
      a: [
        `Rings grow around planets held for ${p.rings} days without a sell. Achievements mark milestones such as being among the first holders, holding a top rank or surviving a catastrophe.`,
      ],
    },
  ],
  disclaimerTitle: "Disclaimer",
  disclaimer: [
    "ORBIT is an entertainment visualisation of public blockchain data. Planets, civilizations, events and achievements are generated by a game simulation and an AI writer; they have no monetary value and are not a promise of anything.",
    "Nothing on this site is financial, investment or legal advice. Crypto tokens are highly volatile and you can lose everything you put in. Do your own research and never invest more than you can afford to lose.",
    "We will never ask you to sign a transaction, share a seed phrase or send tokens. Anyone who does is not us.",
    "ORBIT is an independent project and is not affiliated with NASA or any space agency, nor affiliated with or endorsed by Anthropic. Claude is a trademark of Anthropic.",
  ],
  cta: "Find your planet",
} as const;
