/** All interface copy (English only). Event texts live in @orbit/core/events. */
import type { PlanetClass } from "@orbit/core";

export const copy = {
  agency: "Deep Space Network",
  program: "Holder Exploration Program",
  h1: ["Every holder", "is a world."],
  heroP:
    "Your rank sets the size of your planet. Time held makes it calmer and luckier, but every world lives its own unpredictable story.",
  searchPh: "Paste a wallet address or planet name",
  searchLabel: "Wallet address or planet name",
  find: "Find",
  random: "Fly to a random world",
  top1: "Visit #1",
  notFound: "No planet for that address yet. A planet forms after the first buy.",
  gfeedH: "Mission news",
  legendH: "How the system works",
  legendRule: {
    size: "Size",
    sizeText: " = your rank among holders. ",
    distance: "Distance",
    distanceText: " = time held, oldest closest to the star.",
  },
  legend: [
    ["Supergiant", "#1"],
    ["Gas giants", "#2–10"],
    ["Ice giants", "#11–50"],
    ["Rocky worlds", "#51–200"],
    ["Asteroids", "#201+"],
  ],
  tele: {
    utc: "UTC",
    met: "Mission time",
    objects: "Objects",
    star: "Star",
    mcap: "Market cap",
  },
  demo: "Demo data",
  buy: (ticker: string) => `Buy $${ticker}`,
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  zoomFit: "Show whole system",
  quality: "Graphics quality",
  qualityNames: { auto: "Auto", high: "High", medium: "Medium", low: "Low" },
  canvasLabel: "3D star system where each planet is a token holder",
  loading: "Establishing link…",
  slowLoad: "Still loading the 3D engine. Check your connection or try reloading.",
  noWebgl: "WebGL is not available on this device, so the 3D system can't be shown.",
  sceneError: (msg: string) =>
    `The 3D scene could not start: ${msg}. Try a desktop browser with WebGL enabled.`,
  missionPage: "Mission page",

  cls: {
    super: "Supergiant",
    gas: "Gas giant",
    ice: "Ice giant",
    rocky: "Rocky world",
    asteroid: "Asteroid",
  } satisfies Record<PlanetClass, string>,
  clsPl: {
    super: "Supergiant",
    gas: "Gas giants",
    ice: "Ice giants",
    rocky: "Rocky worlds",
    asteroid: "Asteroids",
  } satisfies Record<PlanetClass, string>,

  theCoin: "The coin",
  classX: "Class",
  copyCA: "Copy CA",
  copyBtn: "Copy",
  copied: "Copied",
  selectedT: "Selected",
  starLore:
    "The star is the coin itself. It grows and changes colour as market cap crosses each threshold. Every world in the system orbits it.",
  mcap: "Market cap",
  worldsOrbit: "Worlds in orbit",
  spectral: "Spectral class",
  nextEvo: "Next evolution",
  max: "Max",
  fully: "Fully evolved",
  supply: "Total supply",
  ignition: "Ignition",
  evo: "Stellar evolution",
  under: "under ",
  flyCloser: "Fly closer",

  kardashev: "Kardashev",
  temp: "Temperature",
  water: "Water",
  atm: "Atmosphere",
  atmU: "atm",
  life: "Life",
  bio: "Biosphere",
  speciesU: "species",
  pop: "Population",
  noCiv: "No civilization",
  tech: "Technology",
  stab: "Stability",
  stabHint: "Grows with time held. Lowers the odds of disasters.",
  newsMore: "Show older news",
  newsNone: "No news yet.",
  civH: "Civilization",
  civNone:
    "No civilization yet. If one appears, its species, capital and beliefs will be described here.",
  speciesL: "Species",
  typeL: "Type",
  lookL: "Appearance",
  capitalL: "Capital",
  ideologyL: "Beliefs",
  mottoL: "Motto",
  findsH: "Rare finds",
  findsNone: "Nothing yet. Rare finds turn up about once a year of planet time.",
  tokens: "Tokens",
  share: "Share of supply",
  since: "Holder since",
  buysSells: "Buys / sells",
  distance: "Distance",
  au: "AU",
  year: "Year length",
  daysU: "days",
  days: (n: number) => `${n} days`,
  hours: (n: number) => `${n} h`,
  achievements: "Achievements",
  badges: [
    ["OG Settler", "Among the first 50 holders"],
    ["Diamond Core", "30+ days, never sold"],
    ["Top 10", "Ranked in the top 10"],
    ["Cradle of life", "Life appeared within 3 days"],
    ["Ring-world", "Reached the Megastructure era"],
    ["Survivor", "Lived through a catastrophe"],
    ["Collector", "Owns a rare find"],
  ],
  ago: {
    now: "just now",
    h: (n: number) => `${n} h ago`,
    d: (n: number) => `${n} d ago`,
  },
  dayN: (n: number) => `Day ${n}`,
  back: "Back to system",
  system: "System",
  active: "Active",
  fastFacts: "Fast facts",
  newsH: "Mission news",
  timelineH: "Mission timeline",
  holderH: "Holder data",
  rankL: "Rank",
  orbitNo: "Orbit",
  ofN: (n: string) => `of ${n}`,
  perDay: "% / day",
  present: "Present",
  sinceDay: (d: number) => `since day ${d}`,
  noLifeYet: "none yet",
  lifeImpossible: "conditions unsuitable",
  starH: "The star",
} as const;

export const LOCALE = "en-GB";
