/** All interface copy (English only). Event texts live in @orbit/core/events. */
import type { PlanetClass } from "@orbit/core";

export const copy = {
  agency: "Deep Space Network",
  program: "Holder Exploration Program",
  h1: ["Every holder", "is a world."],
  heroP:
    "Your rank sets the size of your planet. Time held makes it calmer and luckier, but every world lives its own unpredictable story.",
  searchPh: "Paste a wallet address or planet name",
  searchLabel: "Wallet address or planet name",
  find: "Find",
  random: "Fly to a random world",
  top1: "Visit #1",
  notFound: "No planet for that address yet. A planet forms after the first buy.",
  gfeedH: "Mission news",
  legendH: "How the system works",
  legendRule: {
    size: "Size",
    sizeText: " = your rank among holders. ",
    distance: "Distance",
    distanceText: " = time held, oldest closest to the star.",
  },
  legend: [
    ["Supergiant", "#1"],
    ["Gas giants", "#2–10"],
    ["Ice giants", "#11–50"],
    ["Rocky worlds", "#51–200"],
    ["Asteroids", "#201+"],
  ],
  tele: {
    utc: "UTC",
    met: "Mission time",
    objects: "Objects",
    star: "Star",
    mcap: "Market cap",
  },
  demo: "Demo data",
  rules: "Rules",
  rulesLink: "Read the mission rules",
  buy: (ticker: string) => `Buy $${ticker}`,
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  zoomFit: "Show whole system",
  quality: "Graphics quality",
  qualityNames: { auto: "Auto", high: "High", medium: "Medium", low: "Low" },
  canvasLabel: "3D star system where each planet is a token holder",
  loading: "Establishing link…",
  slowLoad: "Still loading the 3D engine. Check your connection or try reloading.",
  noWebgl: "WebGL is not available on this device, so the 3D system can't be shown.",
  sceneError: (msg: string) =>
    `The 3D scene could not start: ${msg}. Try a desktop browser with WebGL enabled.`,
  missionPage: "Mission page",

  cls: {
    super: "Supergiant",
    gas: "Gas giant",
    ice: "Ice giant",
    rocky: "Rocky world",
    asteroid: "Asteroid",
  } satisfies Record<PlanetClass, string>,
  clsPl: {
    super: "Supergiant",
    gas: "Gas giants",
    ice: "Ice giants",
    rocky: "Rocky worlds",
    asteroid: "Asteroids",
  } satisfies Record<PlanetClass, string>,

  theCoin: "The coin",
  classX: "Class",
  copyCA: "Copy CA",
  copyBtn: "Copy",
  copied: "Copied",
  selectedT: "Selected",
  starLore:
    "The star is the coin itself. It grows and changes colour as market cap crosses each threshold. Every world in the system orbits it.",
  mcap: "Market cap",
  worldsOrbit: "Worlds in orbit",
  spectral: "Spectral class",
  nextEvo: "Next evolution",
  max: "Max",
  fully: "Fully evolved",
  supply: "Total supply",
  ignition: "Ignition",
  evo: "Stellar evolution",
  under: "under ",
  flyCloser: "Fly closer",

  kardashev: "Kardashev",
  temp: "Temperature",
  water: "Water",
  atm: "Atmosphere",
  atmU: "atm",
  life: "Life",
  bio: "Biosphere",
  speciesU: "species",
  pop: "Population",
  noCiv: "No civilization",
  tech: "Technology",
  stab: "Stability",
  stabHint: "Grows with time held. Lowers the odds of disasters.",
  newsMore: "Show older news",
  newsNone: "No news yet.",
  civH: "Civilization",
  civNone:
    "No civilization yet. If one appears, its species, capital and beliefs will be described here.",
  speciesL: "Species",
  typeL: "Type",
  lookL: "Appearance",
  capitalL: "Capital",
  ideologyL: "Beliefs",
  mottoL: "Motto",
  findsH: "Rare finds",
  findsNone: "Nothing yet. Rare finds turn up about once a year of planet time.",
  tokens: "Tokens",
  share: "Share of supply",
  since: "Holder since",
  buysSells: "Buys / sells",
  distance: "Distance",
  au: "AU",
  year: "Year length",
  daysU: "days",
  days: (n: number) => `${n} days`,
  hours: (n: number) => `${n} h`,
  achievements: "Achievements",
  badges: [
    ["OG Settler", "Among the first 50 holders"],
    ["Diamond Core", "30+ days, never sold"],
    ["Top 10", "Ranked in the top 10"],
    ["Cradle of life", "Life appeared within 3 days"],
    ["Ring-world", "Reached the Megastructure era"],
    ["Survivor", "Lived through a catastrophe"],
    ["Collector", "Owns a rare find"],
  ],
  ago: {
    now: "just now",
    h: (n: number) => `${n} h ago`,
    d: (n: number) => `${n} d ago`,
  },
  dayN: (n: number) => `Day ${n}`,
  back: "Back to system",
  system: "System",
  active: "Active",
  fastFacts: "Fast facts",
  newsH: "Mission news",
  timelineH: "Mission timeline",
  holderH: "Holder data",
  rankL: "Rank",
  orbitNo: "Orbit",
  ofN: (n: string) => `of ${n}`,
  perDay: "% / day",
  present: "Present",
  sinceDay: (d: number) => `since day ${d}`,
  noLifeYet: "none yet",
  lifeImpossible: "conditions unsuitable",
  starH: "The star",
  lostH: "Lost worlds",
  destroyed: "Destroyed",
  destroyedLede:
    "The holder sold everything. The planet broke apart; its debris will drift in this orbit for a day. A new world forms if they buy back in.",
  lastRecord: "Last record",
  lastEra: "Last era",
  lived: "Lived",
  debris: "Debris",
} as const;

export const LOCALE = "en-GB";

/** Mission rules page (/rules). Numbers are passed in from the game config. */
export const rulesCopy = {
  title: "Mission rules",
  metaDescription:
    "How ORBIT works: who becomes a planet, what sets its size and orbit, how the simulation runs and what selling does.",
  eyebrow: "Flight rules · Holder Exploration Program",
  h1: ["How a world is born,", "grows and falls."],
  lede: "Every holder of the coin is a planet orbiting the coin-star. The chain decides who you are in the system. The simulation decides what happens to your world. Here is the whole rulebook.",
  back: "Back to system",
  toc: "Contents",
  rules: {
    entry: {
      tag: "Rule 01",
      title: "Entry: hold the minimum",
      lead: (min: string, ticker: string) =>
        `Hold at least ${min} $${ticker} in one wallet and a planet forms for you.`,
      points: (min: string) => [
        `Below ${min} tokens there is no planet: small balances stay as dust in the belt.`,
        "Your wallet is what counts. Tokens spread across several token accounts of the same wallet are added together.",
        `If your balance drops below ${min}, your planet is destroyed, exactly as after a full sell.`,
      ],
      gaugeLabel: "Wallet balance",
      dust: "Dust",
      world: "World forms",
    },
    size: {
      tag: "Rule 02",
      title: "Size = your rank",
      lead: "Your place by balance among all holders sets the class and size of your planet.",
      points: [
        "Ranks are recalculated with every chain snapshot, about once a minute.",
        "When your rank changes, your planet grows or shrinks smoothly.",
      ],
    },
    orbit: {
      tag: "Rule 03",
      title: "Orbit = time held",
      lead: "The longer you hold, the closer you orbit the star. The oldest holder flies nearest.",
      points: [
        "Your hold starts the moment your balance first reaches the minimum.",
        "Buying more never resets your hold start.",
        "Orbits move on a shared clock, so every visitor sees every planet in the same place.",
      ],
      legendOld: "Oldest holders",
      legendNew: "Newest holders",
    },
    sim: {
      tag: "Rule 04",
      title: "The simulation never sleeps",
      lead: (hours: number) =>
        `Every ${hours} hours your planet takes one step of its own history, counted from the start of your hold.`,
      points: (chance: number, astChance: number) => [
        `Each step has a ${chance}% chance of an event: volcanoes, comets, ice ages, wars, golden ages, elections and more (asteroids: about ${astChance}%).`,
        "Time held raises stability. Stable worlds suffer fewer disasters and grow faster.",
        "Bigger planets get a bonus to stability and technology; #1 gets the most.",
        "Life, cities and spaceflight are never guaranteed. Some worlds stay barren forever.",
        "Very rarely a world makes a discovery that stays in its collection for good.",
      ],
      clock: "One step",
      erasTitle: "Eras of a world",
      erasNote: "Eras can also go backwards after wars, pandemics and catastrophes.",
    },
    sell: {
      tag: "Rule 05",
      title: "Selling hits your world",
      lead: "Every sell is measured against your balance just before it. The bigger the share, the harder the strike.",
      ignore: (pct: string) => `under ${pct}: nothing happens`,
      tierRange: (from: string, to: string) => `${from} to under ${to}`,
      tierFull: "100%: everything sold",
      points: (pct: string) => [
        `Sells under ${pct} of your balance go unnoticed.`,
        "A strike lands on your planet's next step: population, biosphere, technology and stability roll back.",
        "Sending tokens to another wallet counts as a sell for you and a buy for the receiver.",
        "Buying never hurts: top-ups only add to your balance.",
      ],
    },
    death: {
      tag: "Rule 06",
      title: "Death and rebirth",
      lead: "Sell everything, or fall below the minimum, and your planet is destroyed.",
      points: [
        "A cloud of debris stays in its orbit for 24 hours.",
        "Its history goes to the archive and is never lost.",
        "Buy back in and a new world forms: the same look (it comes from your address), but progress and hold time start from zero.",
      ],
    },
    rings: {
      tag: "Rule 07",
      title: "Rings and honours",
      lead: (days: number) =>
        `Hold for ${days} days without a single sell and your world earns rings.`,
      points: [
        "Achievements mark the first settlers, diamond hands, the top 10, early life, ring-worlds, survivors and collectors.",
      ],
    },
    star: {
      tag: "Rule 08",
      title: "The star is the coin",
      lead: "The star at the centre is the coin itself. It changes class as the market cap crosses each threshold.",
      under: "under",
      over: "and above",
    },
    news: {
      tag: "Rule 09",
      title: "News from the facts",
      lead: "Mission news reports what the simulation decided. Every number in a story comes from the simulation itself.",
      points: [
        "News appears live, without reloading the page.",
        "Stories never mention prices or give buying or selling advice.",
      ],
    },
    owner: {
      tag: "Rule 10",
      title: "Your planet, your names",
      soon: "Coming soon",
      lead: "Connect your wallet and sign a message to name your planet, species, capital and motto.",
      points: [
        "Only the owner of a planet can change it.",
        "We will never ask you to sign a transaction. Signing in only proves you own the wallet.",
        "Names are checked for abuse and can be reported.",
      ],
    },
    excluded: {
      tag: "Rule 11",
      title: "Who is not a planet",
      lead: "Some accounts hold tokens but are not people. They never appear in the system:",
      points: [
        "the bonding curve and liquidity pools (program accounts),",
        "the burn address,",
        "team wallets.",
      ],
    },
  },
  disclaimer:
    "ORBIT is an entertainment visualisation. Planets, civilizations and events have no monetary value and are not financial advice.",
  cta: "Find your planet",
} as const;
