/**
 * Word lists used by the simulation and event texts. English values from the
 * prototype's W table, in the same order: event params store indexes into
 * these lists, so never reorder or remove entries; only append.
 */
export const W = {
  places: [
    "in the warm equatorial waters",
    "in salty lagoons",
    "under the north polar ice",
    "in hot springs",
    "in a deep ocean rift",
    "in tidal pools",
  ],
  creatures: [
    "six-legged flying whales",
    "glowing fungal forests",
    "crystal worms that sing at sunset",
    "house-sized transparent jellyfish",
    "walking shrubs",
    "three-eyed grazing lizards",
    "fluffy ammonites",
    "giant snails with solar panels on their shells",
    "flocks of boomerang-shaped birds",
    "molluscs that reflect starlight",
    "trees that slowly walk to water",
    "crabs that build perfectly round nests",
  ],
  inventions: [
    "the wheel",
    "writing",
    "the steam engine",
    "radio",
    "a mycelium internet",
    "an AI that refuses to work on Mondays",
    "the quantum toaster",
    "fusion power",
    "a vaccine against boredom",
    "anti-gravity socks",
    "the space elevator",
    "a sock teleporter (socks go missing)",
    "a dark-matter drive",
  ],
  casus: [
    "a dispute over the correct colour of the sky",
    "a national soup recipe",
    "a river that moved the border",
    "an ambassador's bad joke",
    "the right to name the moon",
    "the last slice of cake at a summit",
  ],
  diseases: ["blue fever", "crystal cough", "fungal apathy", "moon itch", "the endless-yawn virus"],
  titles: [
    "High Chancellor",
    "First Navigator",
    "Keeper of the Flame",
    "President",
    "Head Gardener",
  ],
  promises: [
    "to abolish Mondays",
    "free trips to the moon",
    "twice the sunlight",
    "the tallest tower in the system",
    "to finally sort out taxes",
    "never to sell a single stone",
  ],
  ctypes: ["Aquatic", "Subterranean", "Machine", "Nomadic", "Hive mind", "Arboreal"],
  looks: [
    "smooth amphibians with fan-shaped gills",
    "blind six-fingered diggers with superb hearing",
    "self-assembling robots built from local minerals",
    "tall bipeds with translucent crests",
    "a swarm of insect-like beings sharing one mind",
    "slow beings with bark instead of skin",
  ],
  ideology: [
    "worship of the coin-star",
    "pragmatic technocracy",
    "a council of the wisest grandmothers",
    "democracy with a vote every hour",
    "the belief that holding is a virtue",
    "a merchant republic",
  ],
  motto: [
    "We hold to the last atom",
    "Soup first, stars later",
    "Slowly, but to orbit",
    "Not a single stone sold",
    "The night-side lights are our pride",
  ],
  /** [title, description] */
  finds: [
    ["Ruins of an ancient race", "beneath a glacier lies a city older than the planet itself"],
    ["Deep-space signal", "radio telescopes caught a repeating signal from beyond the system"],
    ["Black monolith", "a perfectly smooth black monolith turned up on the far side of the moon"],
    ["Living crystal", "a slowly growing crystal that seems to think was found in a mine"],
    ["Time capsule", "a capsule in a crater reads “Do not open before a $1B market cap”"],
    ["Fossil dragon", "palaeontologists dug up the skeleton of a 300-metre winged reptile"],
  ],
} as const;

/** Syllables for procedural names (English half of the prototype's SY pairs). */
export const SY = [
  "ka",
  "ro",
  "tel",
  "mi",
  "sar",
  "vo",
  "lu",
  "ze",
  "dra",
  "ni",
  "kor",
  "ta",
  "el",
  "um",
  "bra",
  "nes",
  "qua",
  "ri",
  "os",
  "ven",
  "ly",
  "ga",
  "mo",
  "xi",
  "tor",
  "ana",
  "rel",
  "vi",
] as const;

/** Syllables for planet names. */
export const SYL = [
  "va",
  "ro",
  "teth",
  "ka",
  "lun",
  "ze",
  "mar",
  "io",
  "sol",
  "ny",
  "ra",
  "ve",
  "quo",
  "dra",
  "sel",
  "or",
  "an",
  "thy",
  "pex",
  "um",
  "cael",
  "ix",
  "bro",
  "nae",
  "kor",
  "li",
  "sa",
  "vex",
] as const;
